# Generated by Django 5.1.5 on 2025-01-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_caretaker',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('caretaker', 'Caretaker'), ('vocational_school', 'Vocational School')], default='customer', max_length=20),
        ),
    ]
