# Generated by Django 5.1.5 on 2025-01-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0002_remove_customuser_is_caretaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('caretaker', 'Caretaker'), ('vocational_school', 'Vocational School')], default='customer', max_length=20),
        ),
    ]
