# Generated by Django 5.1.5 on 2025-01-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
