# Generated by Django 5.1.5 on 2025-01-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0005_caretakerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretakerprofile',
            name='number_of_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caretakerprofile',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
