# Generated by Django 5.1.5 on 2025-01-30 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0007_remove_caretakerprofile_ratings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='caretaker_profile',
            new_name='caretaker',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('caretaker', 'user')},
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
    ]
