# Generated by Django 5.1.5 on 2025-02-01 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0012_remove_message_parent_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='care_app.reply'),
        ),
    ]
