# Generated by Django 5.1.5 on 2025-02-01 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0013_reply_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
