# Generated by Django 5.1.5 on 2025-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0015_jobpost_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='rate_type',
            field=models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('week', 'Week')], default='hour', max_length=10),
        ),
    ]
