# Generated by Django 5.1.5 on 2025-02-04 09:46

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0017_course_certification_enrollment_vocationalschool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_approved',
            new_name='certification_approved',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='caretaker',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='course',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vocationalschool',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vocationalschool',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='certification',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certification',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='care_app.enrollment'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocationalschool',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vocationalschool',
            name='logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
