# Generated by Django 5.1.5 on 2025-02-04 09:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0018_rename_is_approved_course_certification_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocationalschool',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
