# Generated by Django 5.1.5 on 2025-02-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0020_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('caretaker', 'course')},
        ),
    ]
