# Generated by Django 5.1.5 on 2025-02-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_app', '0022_course_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
